/**
 * Build-time data generator.
 *
 * Clones julearning/metadata from GitHub, reads all subject-level JSON files,
 * flattens sections into individual Document entries, and generates
 * src/data/generated-documents.ts.
 */

import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";

const PROJECT_ROOT = process.cwd();
const OUTPUT_FILE = path.resolve(PROJECT_ROOT, "src/data/generated-documents.ts");
const METADATA_REPO = "https://github.com/julearning/metadata.git";
const CLONE_DIR = path.resolve(os.tmpdir(), "julearning-metadata-" + Date.now());

function cloneMetadata() {
  console.log("Cloning julearning/metadata...");
  fs.mkdirSync(CLONE_DIR, { recursive: true });
  try {
    execSync(`git clone --depth 1 ${METADATA_REPO} "${CLONE_DIR}"`, {
      stdio: "pipe",
      timeout: 60_000,
    });
    console.log("Metadata cloned.");
  } catch (err) {
    console.error("Failed to clone metadata repository:", err.message);
    process.exit(1);
  }
}

function getFileIdFromUrl(url) {
  const match = url.match(/\/file\/d\/([^/]+)\//);
  return match ? match[1] : null;
}

function getThumbnailUrl(url) {
  const fileId = getFileIdFromUrl(url);
  if (!fileId) return "";
  return `https://drive.google.com/thumbnail?id=${fileId}&sz=w1000`;
}

function inferFileType(url) {
  if (url.includes("document/d/") || url.endsWith(".docx")) return "docx";
  return "pdf";
}

function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .replace(/--+/g, "-");
}

function scanDir(dir) {
  const subjectFiles = [];

  function scan(currentDir) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        scan(fullPath);
      } else if (entry.name.endsWith(".json") && !entry.name.startsWith(".")) {
        subjectFiles.push(fullPath);
      }
    }
  }

  scan(dir);
  return subjectFiles;
}

function flattenDocuments(subjectFiles) {
  const docs = [];
  let idCounter = 1;

  for (const filePath of subjectFiles) {
    try {
      const raw = fs.readFileSync(filePath, "utf-8");
      const subjectData = JSON.parse(raw);

      if (!subjectData.subject || !subjectData.branch || !subjectData.semester) {
        console.warn("Skipping " + filePath + ": missing required fields");
        continue;
      }

      const branch = subjectData.branch;
      const semester = subjectData.semester;
      const subject = subjectData.subject;
      const sections = subjectData.sections || {};

      const allChapters = [];
      for (const [sectionKey, sectionData] of Object.entries(sections)) {
        if (sectionData && sectionData.chapters) {
          allChapters.push(...sectionData.chapters);
        }
        if (sectionData && sectionData.documents) {
          for (const doc of sectionData.documents) {
            if (!doc.title || !doc.url) {
              console.warn("Skipping doc in " + filePath + ": missing title or url");
              continue;
            }

            const id = `doc-${String(idCounter).padStart(4, "0")}`;
            idCounter++;

            const fileType = doc.fileType || inferFileType(doc.url);
            const chapters = sections[sectionKey]?.chapters || [];

            docs.push({
              id,
              title: doc.title,
              description: doc.description || `${subject} — ${sectionKey.replace("section-", "Section ").toUpperCase()}`,
              url: doc.url,
              thumbnailUrl: getThumbnailUrl(doc.url),
              fileType,
              fileSize: doc.fileSize || 0,
              branch,
              semester,
              subject,
              section: sectionKey,
              tags: doc.tags || [],
              chapters,
              contributor: doc.contributor || "",
              uploadedAt: doc.uploadedAt || new Date().toISOString(),
              language: doc.language || "English",
              pages: doc.pages,
              downloads: doc.downloads,
            });
          }
        }
      }
    } catch (e) {
      console.warn("Error reading " + filePath + ": " + e.message);
    }
  }

  return docs;
}

function generateFile(docs) {
  const json = JSON.stringify(docs, null, 2);
  const lines = [
    "// Auto-generated at build time. Do not edit.",
    "// Generated by scripts/generate-data.mjs from julearning/metadata",
    "",
    'import type { Document } from "@/lib/types";',
    "",
    "export const documents: Document[] = " + json + ";",
    "",
    "export function getUniqueBranches(): string[] {",
    '  return [...new Set(documents.map((d: Document) => d.branch))];',
    "}",
    "",
    "export function getUniqueSubjects(branch?: string): string[] {",
    "  const filtered = branch ? documents.filter((d: Document) => d.branch === branch) : documents;",
    "  return [...new Set(filtered.map((d: Document) => d.subject))].sort();",
    "}",
    "",
    "export function getUniqueSemesters(branch?: string): number[] {",
    "  const filtered = branch ? documents.filter((d: Document) => d.branch === branch) : documents;",
    "  return [...new Set(filtered.map((d: Document) => d.semester))].sort((a: number, b: number) => a - b);",
    "}",
    "",
    "export function getDocumentsByBranch(branch: string): Document[] {",
    "  return documents.filter((d: Document) => d.branch === branch);",
    "}",
    "",
  ];
  return lines.join("\n");
}

function cleanup() {
  fs.rmSync(CLONE_DIR, { recursive: true, force: true });
  console.log("Temp metadata cleaned up.");
}

try {
  cloneMetadata();

  console.log("Scanning for metadata files...");
  const subjectFiles = scanDir(CLONE_DIR);
  console.log(`Found ${subjectFiles.length} subject-level JSON files`);

  const docs = flattenDocuments(subjectFiles);
  console.log(`Flattened into ${docs.length} documents`);

  const content = generateFile(docs);
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");

  console.log("Generated " + OUTPUT_FILE);
} finally {
  cleanup();
}
