/**
 * Build-time data generator.
 *
 * Clones julearning/metadata from GitHub, reads all JSON files,
 * and generates src/data/generated-documents.ts with embedded document data.
 *
 * Runs via prebuild / predev in package.json.
 * No external arguments needed — it clones the repo itself.
 */

import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import os from "os";

const PROJECT_ROOT = process.cwd();
const OUTPUT_FILE = path.resolve(PROJECT_ROOT, "src/data/generated-documents.ts");
const METADATA_REPO = "https://github.com/julearning/metadata.git";
const CLONE_DIR = path.resolve(os.tmpdir(), "julearning-metadata-" + Date.now());

function cloneMetadata() {
  console.log("Cloning julearning/metadata...");
  fs.mkdirSync(CLONE_DIR, { recursive: true });
  try {
    execSync(`git clone --depth 1 ${METADATA_REPO} "${CLONE_DIR}"`, {
      stdio: "pipe",
      timeout: 60_000,
    });
    console.log("Metadata cloned.");
  } catch (err) {
    console.error("Failed to clone metadata repository:", err.message);
    process.exit(1);
  }
}

function scanDir(dir) {
  const docs = [];
  if (!fs.existsSync(dir)) return docs;

  function scan(currentDir) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        scan(fullPath);
      } else if (entry.name.endsWith(".json") && !entry.name.startsWith(".")) {
        try {
          const raw = fs.readFileSync(fullPath, "utf-8");
          const doc = JSON.parse(raw);
          if (doc.id && doc.title && doc.url) {
            docs.push(doc);
          } else {
            console.warn("Skipping " + fullPath + ": missing required fields");
          }
        } catch (e) {
          console.warn("Skipping " + fullPath + ": " + e.message);
        }
      }
    }
  }

  scan(dir);
  return docs;
}

function generateFile(docs) {
  const json = JSON.stringify(docs, null, 2);
  const lines = [
    "// Auto-generated at build time. Do not edit.",
    "// Generated by scripts/generate-data.mjs from julearning/metadata",
    "",
    'import type { Document } from "@/lib/types";',
    "",
    "export const documents: Document[] = " + json + ";",
    "",
    "export function getUniqueBranches(): string[] {",
    '  return [...new Set(documents.map((d: Document) => d.branch))];',
    "}",
    "",
    "export function getUniqueSubjects(branch?: string): string[] {",
    "  const filtered = branch ? documents.filter((d: Document) => d.branch === branch) : documents;",
    "  return [...new Set(filtered.map((d: Document) => d.subject))].sort();",
    "}",
    "",
    "export function getUniqueSemesters(branch?: string): number[] {",
    "  const filtered = branch ? documents.filter((d: Document) => d.branch === branch) : documents;",
    "  return [...new Set(filtered.map((d: Document) => d.semester))].sort((a: number, b: number) => a - b);",
    "}",
    "",
    "export function getDocumentsByBranch(branch: string): Document[] {",
    "  return documents.filter((d: Document) => d.branch === branch);",
    "}",
    "",
  ];
  return lines.join("\n");
}

function cleanup() {
  fs.rmSync(CLONE_DIR, { recursive: true, force: true });
  console.log("Temp metadata cleaned up.");
}

// ─── Main ────────────────────────────────────────────────────────────

try {
  cloneMetadata();

  console.log("Scanning for metadata files...");
  const docs = scanDir(CLONE_DIR);

  const content = generateFile(docs);
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");

  console.log("Generated " + OUTPUT_FILE + " with " + docs.length + " documents");
} finally {
  cleanup();
}
