/**
 * Build-time data generator.
 * Scans ../metadata/ for JSON files and generates
 * src/data/generated-documents.ts with all document data embedded.
 *
 * Runs via prebuild / predev in package.json.
 */

import fs from "fs";
import path from "path";

// Use process.cwd() — __dirname is undefined in ESM .mjs files
const PROJECT_ROOT = process.cwd();
console.log("PROJECT_ROOT:", PROJECT_ROOT);
const METADATA_DIR = path.resolve(PROJECT_ROOT, "../metadata");
console.log("METADATA_DIR:", METADATA_DIR);
const OUTPUT_FILE = path.resolve(PROJECT_ROOT, "src/data/generated-documents.ts");

function scanMetadataDir(dir) {
  const docs = [];

  if (!fs.existsSync(dir)) {
    console.warn("Metadata directory not found:", dir);
    return docs;
  }

  function scan(currentDir) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);
      if (entry.isDirectory()) {
        scan(fullPath);
      } else if (entry.name.endsWith(".json") && !entry.name.startsWith(".")) {
        try {
          const raw = fs.readFileSync(fullPath, "utf-8");
          const doc = JSON.parse(raw);
          if (doc.id && doc.title && doc.url) {
            docs.push(doc);
          } else {
            console.warn("Skipping " + fullPath + ": missing required fields");
          }
        } catch (e) {
          console.warn("Skipping " + fullPath + ": " + e.message);
        }
      }
    }
  }

  scan(dir);
  return docs;
}

function generateFile(docs) {
  const json = JSON.stringify(docs, null, 2);
  const lines = [
    "// Auto-generated at build time. Do not edit.",
    "// Generated by scripts/generate-data.mjs from ../metadata/",
    "",
    'import type { Document } from "@/lib/types";',
    "",
    "export const documents: Document[] = " + json + ";",
    "",
    "export function getUniqueBranches(): string[] {",
    '  return [...new Set(documents.map((d: Document) => d.branch))];',
    "}",
    "",
    "export function getUniqueSubjects(branch?: string): string[] {",
    "  const filtered = branch ? documents.filter((d: Document) => d.branch === branch) : documents;",
    "  return [...new Set(filtered.map((d: Document) => d.subject))].sort();",
    "}",
    "",
    "export function getUniqueSemesters(branch?: string): number[] {",
    "  const filtered = branch ? documents.filter((d: Document) => d.branch === branch) : documents;",
    "  return [...new Set(filtered.map((d: Document) => d.semester))].sort((a: number, b: number) => a - b);",
    "}",
    "",
    "export function getDocumentsByBranch(branch: string): Document[] {",
    "  return documents.filter((d: Document) => d.branch === branch);",
    "}",
    "",
  ];
  return lines.join("\n");
}

// Main
console.log("Generating search data from metadata...");

const docs = scanMetadataDir(METADATA_DIR);
const content = generateFile(docs);

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, content, "utf-8");

console.log("Generated " + OUTPUT_FILE + " with " + docs.length + " documents");
