/**
 * Document data source.
 *
 * At build time, scripts/generate-data.mjs scans the ../metadata/ directory
 * and generates src/data/generated-documents.ts with all document data.
 * This file re-exports from the generated file.
 *
 * In development without a metadata directory, run:
 *   npm run generate
 */

// This import is resolved from the file generated by scripts/generate-data.mjs
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import type { Document } from "@/lib/types";

export {
  documents,
  getUniqueBranches,
  getUniqueSubjects,
  getUniqueSemesters,
  getDocumentsByBranch,
} from "./generated-documents";
